Define the axios request body to be of type unknown:
Fixes errors caused when the API request body is just a json bool. 

For example:
```
Error: src/app/client/services.gen.ts(88,159): error TS2345: Argument of type '{ url: string; data?: any; path: Record<string, unknown> & { name: string; }; method?: "connect" | "delete" | "get" | "head" | "options" | "patch" | "post" | "put" | "trace"; timeout?: number; ... 42 more ...; headers: { "if-match": string; }; }' is not assignable to parameter of type 'RequestOptionsBase'.
  Types of property 'body' are incompatible.
    Type 'boolean' is not assignable to type 'number | unknown[] | Record<string, unknown> | BodyInit | Record<string, unknown>[] | null | undefined'.
```

Signed-off-by: Hiram Chirino <hiram@hiramchirino.com>